# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDBlog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDBlog
  pod 'Alamofire', '~> 4.2.0'
  pod 'SnapKit', '~> 3.1.2'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Kingfisher', '~> 3.2.4'
  pod 'SVProgressHUD', '~> 2.1.2'
end
